# Generated by Django 3.2.6 on 2021-08-13 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diccionario_QUECHUA_ESP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palabradb_quechua', models.CharField(max_length=100, verbose_name='Palabra en Quechua')),
                ('palabradb_esp', models.CharField(max_length=100, verbose_name='palabra en español (Traduccion)')),
                ('palabradb_ejemplo_uso', models.TextField(verbose_name='Contexto o ejemplo de uso')),
            ],
        ),
    ]
